apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reservations
  name: reservations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservations
  template:
    metadata:
      labels:
        app: reservations
    spec:
      containers:
        - image: us-east4-docker.pkg.dev/driven-fragment-422607-h2/reservations/production
          name: reservations
          env:
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: connectionString
