apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - image: us-east4-docker.pkg.dev/driven-fragment-422607-h2/auth/production
          name: auth
          env:
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: connectionString
