name: Build Docker Image CI

on:
  push:

jobs:
  docker-build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Enable Debug Logging
        run: |
          echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_OUTPUT

      - name: checks docker image list
        run: docker images

      - name: test
        run: echo "name=${{ secrets.DOCKERHUB_USERNAME }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: checks docker image list
        run: docker images
