name: Build Docker Image CI

on:
  push:

jobs:
  build_reservations:
    uses: JialinWang1/actions/.github/workflows/build_and_push_docker_image.yml@v2
    with:
      docker_file: 'apps/reservations/Dockerfile'
      tag: 'garrinwang/sleeper-reservations:latest'
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
