name: Build Docker Image CI

on:
  push:

jobs:
  docker-build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable Debug Logging
        run: |
          echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_OUTPUT

      - name: test
        run: echo "name=${{ secrets.DOCKERHUB_USERNAME }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build image
        run: docker build -t garrinwang/sleeper-reservations:$(date +%s) -f apps/reservations/Dockerfile .

      - name: push image
        run: docker push garrinwang/sleeper-reservations:$(date +%s)
