name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:
    uses: JialinWang1/actions/.github/workflows/docker-login.yml@main
    with:
      token: ${{ secrets.DOCKERHUB_TOKEN }}
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      
    
  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: run docker
        run: |
          docker images
