name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:
    uses: JialinWang1/actions/.github/workflows/docker-login.yml@v1
       
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: run docker
        run: |
          docker images
