name: Docker Image CI

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Use Docker Login from Repo A
       uses: JialinWang1/actions/.github/workflows/docker-login.yml@v1
       
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: run docker
        run: |
          docker images
